import type { Product } from '../product-card';

export const mockProductList: Product[] = [
  {
    id: 101,
    title: "Eco-friendly Water Bottle",
    description: "Reusable and durable water bottle.",
    price: 15.99,
    discountPercentage: 5.0,
    rating: 4.7,
    stock: 150,
    brand: "GreenLife",
    category: "eco-friendly",
    thumbnail: "https://cdn.dummyjson.com/product-images/101/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/101/1.jpg"],
  },
  {
    id: 102,
    title: "Wireless Charging Pad",
    description: "Fast wireless charging for compatible devices.",
    price: 29.99,
    discountPercentage: 10.0,
    rating: 4.5,
    stock: 200,
    brand: "TechGear",
    category: "electronics",
    thumbnail: "https://cdn.dummyjson.com/product-images/102/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/102/1.jpg"],
  },
  {
    id: 103,
    title: "Organic Cotton T-Shirt",
    description: "Soft and comfortable t-shirt made from organic cotton.",
    price: 25.00,
    discountPercentage: 0,
    rating: 4.8,
    stock: 120,
    brand: "PureWear",
    category: "apparel",
    thumbnail: "https://cdn.dummyjson.com/product-images/103/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/103/1.jpg"],
  },
  {
    id: 104,
    title: "Bluetooth Noise-Cancelling Headphones",
    description: "Immersive sound experience with noise-cancelling technology.",
    price: 199.50,
    discountPercentage: 15.0,
    rating: 4.9,
    stock: 75,
    brand: "SoundWave",
    category: "electronics",
    thumbnail: "https://cdn.dummyjson.com/product-images/104/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/104/1.jpg"],
  },
  {
    id: 105,
    title: "Stainless Steel Coffee Tumbler",
    description: "Keeps your coffee hot for hours.",
    price: 22.00,
    discountPercentage: 0,
    rating: 4.6,
    stock: 90,
    brand: "HotNCold",
    category: "kitchenware",
    thumbnail: "https://cdn.dummyjson.com/product-images/105/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/105/1.jpg"],
  },
   {
    id: 106,
    title: "Yoga Mat Premium",
    description: "High-density, non-slip yoga mat.",
    price: 35.00,
    discountPercentage: 5.0,
    rating: 4.7,
    stock: 60,
    brand: "ZenFlow",
    category: "sports",
    thumbnail: "https://cdn.dummyjson.com/product-images/106/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/106/1.jpg"],
  }
];
